spring:
  datasource:

    platform: postgres
    driverClassName: org.postgresql.Driver

    url: jdbc:postgresql://ec2-176-34-105-15.eu-west-1.compute.amazonaws.com:5432/d4j0h6n8act2bl
    username: zmdjsbvtocpoyf
    password: 403fa3e20d7d93678833691bc707d41a0960e24ca6bb552c5eab61032d59fbdd

    hikari:
      connection-timeout: 20000
      maximum-pool-size: 1

#    initialization-mode: always
    initialization-mode: never

  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: none


  jackson:
    visibility:
      field: any

jwt:
  secret: my_secret_secret
  validityInMinutes: 20

api.key: da1527aa9873cf2261a2c9c132f04e66
currency.api.uri: http://data.fixer.io/api/latest